# Mein Kommentar

# Um wie viele Pixel soll bei Strg-Cursor das Bild verschoben werden.
delta_pfeiltasten = 50

# Ab wieviel Grad Schrägstellung wird ein Bild zurückgedreht
min_winkel = 0.25

# Wie viele Pixel soll der Rand um Kontrollbilder größer sein,
# als es den gewählten Bild-Ecken entsprechen würde.
rand = 20

# Eingegebenen Rand um Wert vergrössern
rahmen_plus = -7

[pfade]
# Verzeichnis, das zuletzt verwendet wurde
pic_path = "C:\\Users\\Klaus\\Pictures\\testpics"

# Unterverzeichnis von pic_path zur AUsgabe
# Wird angelegt, wenn nicht existent
pic_output = "zerlegt"

# Endung nach der in pic_path gesucht wird
pic_type = '.tif'

[scale]
# Fuer erste Anzeige kompletter Seite
seite = 0.1

# Fuers Setzen der Ecken
ecke  = 0.5 

# Fuer finale Kontrollanzeige
kontrollbild  = 0.2 
