[[seite]]
datei = 'd1'

[[seite.foto]]
nr = 1
datei = 'f1'
[[seite.foto.ecke]]
x = 10
y = 11
[[seite.foto.ecke]]
x = 20
y = 21
[[seite.foto.ecke]]
x = 30
y = 31

[[seite.foto]]
nr = 2
datei = 'f2'
[[seite.foto.ecke]]
x = 210
y = 211
[[seite.foto.ecke]]
x = 220
y = 221
[[seite.foto.ecke]]
x = 230
y = 231

[[seite]]
datei = 'd1'

[[seite.foto]]
nr = 1
datei = 'f1'
[[seite.foto.ecke]]
x = 10
y = 11
[[seite.foto.ecke]]
x = 20
y = 21
[[seite.foto.ecke]]
x = 30
y = 31
