title = "Seitenliste"
wert = "234"
[[seite]]
# ------------------------------------------
pfad = "filename1"
[[seite.foto]]
nr = 1
rahmen_plus = 10
x1 = 11
y1 = 12
x2 = 21
y2 = 22
x3 = 31
y3 = 32

[[seite.foto]]
nr = 2
rahmen_plus = 10
x1 = 211
y1 = 212
x2 = 221
y2 = 222
x3 = 231
y3 = 232

[[seite]]
# ------------------------------------------
pfad = "filename2"
[[seite.foto]]
nr = 1
rahmen_plus = 10
x1 = 311
y1 = 312
x2 = 321
y2 = 322
x3 = 331
y3 = 332
